# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:push or pull events
  # Triggers the workflow on push or pull events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually requested from the main branch
  workflow_dispatch:Manual

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:parallel or sequential
  # This workflow contains a single job called "build"
  build:PB001
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
